import os
COMMAND_PREFIX = "> "
DISCORD_CHANNEL_ART_GALLERY = "art-gallery"
DISCORD_CHANNEL_WAIFU_WARS = "waifu-husbando-war"
DIR_OUTPUT = os.path.join(os.getcwd(), "io")
DISCORD_MESSAGES_LIMIT = 10000
NOT_APPROVE_SIGN = "❎"
APPROVE_SIGN = "✅"
SET_APPROVE_SIGN = "☑️"
WAIFUWARS_ATTACK_SIGN = "🗡️"
WAIFUWARS_ATTACKED_SIGN = "🚑"
WAIFUWARS_CONCEDE_SIGN = "🏳️"